version: "3"
services:
  reverse-proxy:
    image: traefik:v2.9
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # App runner
  bsns_poc:
    build: ./
    labels:
      - "traefik.http.routers.bsns_poc.rule=Host(`medhead.localhost`) && PathPrefix(`/poc`)"
      - "traefik.http.routers.bsns_poc.middlewares=poc-stripprefix"
      - "traefik.http.middlewares.poc-stripprefix.stripprefix.prefixes=/poc"
      - "traefik.http.services.bsns_poc.loadbalancer.server.port=9000"

  # Redis dependency
  redis:
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./:/app